apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: inventory-prod
data:
  PORT: "3000"
  DATABASE: "inventory_db"
  COLLECTION: "items"
  CACHE_TTL: "300"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MONGO_PORT: "27017"
